apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wireguard
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wg-easy
      version: "5.3.x"
      sourceRef:
        kind: HelmRepository
        name: wg-easy
        namespace: flux-system
      interval: 1m
  values:
    # This ensures the WireGuard server runs on your powerful ProBook node
    nodeSelector:
      kubernetes.io/hostname: quinn-hpprobook430g6
    
    # Configure the LoadBalancer service to expose the VPN port and Web UI
    service:
      # Exposes the main VPN port
      wg:
        type: LoadBalancer
        # This is the standard WireGuard port
        port: 51820
      # Exposes the management Web UI
      ui:
        type: LoadBalancer
        port: 51821
        
    # This tells the pod to load its environment variables (including the password)
    # from the Kubernetes secret you created, rather than from plain text.
    extraEnvVarsSecret: wireguard-admin-password
    
    host: quinnshomelab.ddns.net

    # Use persistence for the configuration
    persistence:
      enabled: true
      storageClassName: local-storage
      size: 1Gi

