apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  # This explicitly binds this PVC to the correct PV
  volumeName: wireguard-config-pv
