apiVersion: v1
kind: Secret
metadata:
    name: ansible-mcp-secrets
    namespace: apps
type: Opaque
stringData:
    ANSIBLE_CONTROLLER_URL: ENC[AES256_GCM,data:ihW1OPw64zq9lqfQ5yYKV3arY9l3/vw=,iv:QwvcUb4p/BlSVLTngkyZNjHQUYETLHlYUiwZO/V6GI4=,tag:ZSgfnhjFbHtPLTQAGmtCqA==,type:str]
    ANSIBLE_CONTROLLER_TOKEN: ENC[AES256_GCM,data:Pj7HZ5ab6V1hcRUkr9PWgFTg3baAlOm/AZU8uWwe,iv:WpDcd6dZ4Kf9z80vPPwxbLekRimpdvOXrwvSe0xx428=,tag:ZuLB6+fWrqx8Tf9vGgTESQ==,type:str]
    ANSIBLE_VERIFY_SSL: ENC[AES256_GCM,data:2j9paFA=,iv:0KDrIX8MjNcRtvC3ZMeoLQwo1pgBuun2B8gP7z95LFM=,tag:tS9h9Vpt1d7RiCsXFoeDNQ==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUFZZWE5NDNqOGhUamNh
            K2hEYjZIWUVMRXZhMTNyQmhaMXA5OTVibmxJCnI3dVFwUGxINjhmTzM2MjN1TkM5
            ck1sWCtRWXRjTDdITkhucWVnTEJXRVEKLS0tIHQ3SktEUHRkeDBvRzlydUdYeVJP
            eVhMTUlUaGdZSEtpd0d3dG9sM2VURzQKV2PFo0SASk40dwimCoRXp8wmChE9IO8w
            ZxvMX6JFviSEzMw2e+rf8/OeHmdSPh71GSu0IvA7V0/vhy4nhYSf5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:fqZEQ45cdlfzEPy4S+FX4bS3xGHniuFScpb4CdMsU0D5czU5cogh4dGh9g71vOJQZiWFhhi/D/gYY/EFvfHQSOwTVnltLG7eVyzNSarTMKepB8tyvB8XmMKn1FqErnD+cQkzh4//OVYfypZbduePEMOmg2G0qUbflxQzgSdKLBo=,iv:fH4nCb18lhSQADPrgrtlKmaBZkT2HBPkjFjmS0kJSj4=,tag:huGvVnA4ypefC/z0wv/LzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
