apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany # Multiple pods could read from this
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/Cruzer4GB # The path to the media store(usb drive on raspberry pi)
    server: 192.168.1.21   