apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-calico-vxlan
  namespace: kube-system
spec:
  template:
    spec:
      hostNetwork: true
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: cleanup
        image: docker.io/calico/node:v3.29.1
        command: ["/bin/sh", "-c"]
        args: ["ip link delete vxlan.calico || echo 'Interface not found'"]
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      restartPolicy: Never
