---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: apps
  labels:
    app: authentik
type: Opaque
stringData:
  # Generated secret key
  AUTHENTIK_SECRET_KEY: "csspMU7PuYJMQ7MgfZI8yKo4XjHXgv8f5mnpl+Bg/wtca17lnsHAJ7mxGiOaHn2yGY8j2ZzP5Hcck1fh6"
  # Postgres password for authentik user
  AUTHENTIK_POSTGRESQL__PASSWORD: "authentik123"
