apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: apps
    labels:
        app: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0OXZC/NmzqV003AiW42hYl8oXDYG,iv:h6IKy6aaLDrZcyoSTmP9dNbCnjXyE33btKq41sENZDU=,tag:jYsfT01xTH7Z9niinDCxRA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:fyqyosfDntBewIoYQ6H6pTB3DA//U4BtE4GHOnMP4PLCMS1knmdJLPLFFE1IYGQ/Fz9X32irAlgEg9LkQSB1IHKM/pS7kEPlCiIHlh70P4iJ,iv:PqKI6470HCyyQ3dggnQt/7WRRmC+/EKWcIGxVY7usKo=,tag:h0MY0FeXWQlMNFTbsFYq/g==,type:str]
    #ENC[AES256_GCM,data:HU1FQO4Ci42dr1gdJMavKrDCc4hC1kyS1QrKWE3MjyoGleOZtA==,iv:tgf9ye+vzm2MnfGSJNJPolfhrOUvyQ6DhVyP2fjtF3I=,tag:oo764U+vPnUizMKvUGoKVw==,type:comment]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:t1LW3ZPzLysneJuJ,iv:6rDAK9gPFX3D79hz9WPVhZi20NYTxWfuc6zYy+tU8qw=,tag:TFKEFegAhxkgUOpwIZOlIg==,type:str]
    #ENC[AES256_GCM,data:g/fh6dK4mOhWv/g5ep+crJUZxQurLj+eb8XSAgPLK5tmesJ1yijy4XhzVA2vOr93vjlfOcWasYPKaemn,iv:HNI2wOwp/cftHZtgYGvc+cxeMRo2xdOnjzY5oC2sIpU=,tag:NzuSwNl0NQJoenWUhVn9FA==,type:comment]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:lzjk7nrnIrloc0awNyYcqbuhsg==,iv:7yzqaxUnzz0wX6rxIucMhhwQlL89McN7vsnVG/hAVWQ=,tag:xJgvBlt1Ysp6RCBil1lb7Q==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRExtRHNHUk5abzlOR2RN
            S3ZQOWVEMG85WThOa0JxdnYyczNhRUx1NlhBCmtROU94NVBMcDUxVysrVHJscWd0
            d01TdjZneEs2MjJ0dkh5dzdjLzZLRWsKLS0tIDVYQk1MbUdQWXpVcjZnT2tTMkxF
            a2hMNFNyVk5qK2tYNWNJaFRITFlvTEUKMkxTVlV7D94/WN/75zQgb7/RK1RlHOd4
            agwI8QCc4OuuUFYOzHhduuvLyODmzbRycWTd9VKgLeh7sc0d5U1GLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:dcQ6YKp736dejmtFrDQCQs2cW7jLkXg2YGzSNLmNdqPnCpVkujEn3YSZOr/a5qSMep1b3FXjg/srwHXCEyV+NCCY3x6AmRTZk7u969vCNeJ8yV8v6AGWdihWtnySHLl0LAyUGd9YujvmomBa9Oyj7EcSEvwjNw0EDy2qXdYIRw0=,iv:h6jDtF7i4aaPGUuCuJaSGjEU+WKgXNjz6ARjFD9yV+g=,tag:hChCYM2vYrB95bJo3lJnjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
