apiVersion: v1
kind: Secret
metadata:
    name: context-forge-secrets
    namespace: apps
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:pfGuY/x/6f+HNuOXZ9OyOjD9NOHELVdL5cOnvTit4H05rlOeG98=,iv:D4LlTWWOD5tKPrtjg9960SyxX1Cazt1GCUpRAW25gr0=,tag:mEzEXr2eMK8Ml+uqsg9wuw==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:ZMJIiVxVP0Fz,iv:Kzyj8wZrMHsW9/CidrdZoS1Qlly4XQ7JYJEqEAxPJiw=,tag:1r3ObvozajEMjPGB5yfuXA==,type:str]
    PLATFORM_ADMIN_PASSWORD: ENC[AES256_GCM,data:2G8r7gzvP5eqtz4+IY/UhqJGsUKIoK9x9/bc1Myirfo=,iv:8ZyoRDDj8VWRruJE71U35u60kpPC55d6/buKzEQ3Bas=,tag:vAJcG5iqvoXoaKfShSQLcQ==,type:str]
    DEFAULT_USER_PASSWORD: ENC[AES256_GCM,data:ld70gMtSyvLUpUjDNZSczyunPIDbsr3aLRtuIowcM+8=,iv:ps8Q0uewZ2ca3WIbLI2KfkDKI5HRAfrwKWbefmDGYKE=,tag:h2pn64y0snR0DehLTRKEsA==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SGJDTUtsNGlpZVZFcFU5
            MzdicUNhc09YTTNKVVFDVTNydVRhSWxqbldvCnV3b0QrS1drOCtrN01GbzI5SVJ6
            bXExM3BKSEVacnVYbER4UzZqeGFPTWsKLS0tIGx3UkxvYlA3cUY0UVNZL2JzdVcr
            TlVPL0VBYmxteUpBZTlOUzBpZ2JmZncKnPicFvM4DkQACUYPsmm++6znXzQIVXch
            5sHRDB4rwbsCJTLcW+qjeXrTzWwJ1LrfduMI32Z2JO4NeoBSAWOi5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:TS3iUqpnUgSzmEC+yUAQqdmP2OoW4qkp70ENeoxrPCXZwDnHslMolMznFcx99WvDmzxnZcUzoVtnSyg033Z9x1nrRJvMcanbgOthkRh2K9Kbp5itK2jeCTGSPF8PzCB3Mel/y137la8jpRvT3cMWAIW9J22yMNHFgyd/LPX5aLo=,iv:YE1ClF4awzq8lQNgy0h2Bv8F6ktJEcNRQC2kSnbM1ZA=,tag:N4nw/pRD5Inv1yDlmfea0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
