apiVersion: v1
kind: Secret
metadata:
    name: context-forge-secrets
    namespace: apps
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:70eQATkV3wweIjLnQvp72X7WnNDEpvslIaypd982ngnEm4Hyscc=,iv:oYwJ7LDlWXdHi5R4/F1kxNFVPtiUJ55h1T44ofGricM=,tag:tRM3BDOeYoR8T/T/LOr4pQ==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:bvznHor8V+BC,iv:wa8rlJXsts37AW2aTQlRUEPmGgWFz2+Q3L6aEWQ6Hb0=,tag:IjCPmBmzPuaTYcFwMZX4Bw==,type:str]
    PLATFORM_ADMIN_PASSWORD: ENC[AES256_GCM,data:a04i9NJTDyPrWaSClKMfZ41MTn6JuMIfGNKvpVyc/bo=,iv:J2/dGrnEYrjZW0FbqX110KWusAiGuKvkTFUdQBwBU2c=,tag:Qyn1pQ+t5zxmgiGXLaoPkA==,type:str]
sops:
    age:
        - recipient: age1lcl4x9eckuj7skyjq26h4e70dl2qvjec3saerxzunp8z7r28e3qsd0c8d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIckV3UTlZL2k1VGg2ZEhF
            SlU1cy9Ka2ltbG5HNUhIb0hueUF4WTVnakNRCmhodUFkUGpRL0ZnejhSOW9iOXVI
            eWtEMis5K0RVdnMvT2hmWEZMTkVmWXcKLS0tIHphUVhrZEJkRWxEVW5JOGU2ZkRP
            S0NWWVEraHpVK3VteUxIa3E0eFFnMGMKu7gq4QJTNljJt2F1qSIrDifRqNJNbaX9
            HDdQIt+BQimZy+2DOMu429hIm6cPKjoVwPp7WxHGWdMQW3iB95uUqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T09:13:55Z"
    mac: ENC[AES256_GCM,data:mNf3F3oN826WK7U84mAC+LOvJbp1Z/6Yu4bZCGOkAqCsnB6t9AjlGSKK8agsnyOEJPlYOsmK2404sXmerOMoDhBdEwQ5spVOg/gXe53JEQHzq9fYa9b37ELcqOLhHAyge2mHviMRch5SCgteRjf5YPgl/T2/aCTFBWYcQhRHcys=,iv:MWCEdMTnQPQfnJEIxvXWuFyhKzmwtmdf/UVQUC07MKg=,tag:zmd+79kj2YqpJ88d6igKeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
