apiVersion: v1
kind: Secret
metadata:
    name: context-forge-secrets
    namespace: apps
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:3LSkDp8wBYQHVo8pgGvEYqi205nmwfPJgXjoMxwf+3QU5nVYDhg=,iv:D4LlTWWOD5tKPrtjg9960SyxX1Cazt1GCUpRAW25gr0=,tag:w2q54K8ZlS0zrDItdzg0Ew==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:vwVa2IYLLH/H,iv:Kzyj8wZrMHsW9/CidrdZoS1Qlly4XQ7JYJEqEAxPJiw=,tag:7/Th0KPKSNRGpcpsehx2fQ==,type:str]
    PLATFORM_ADMIN_PASSWORD: ENC[AES256_GCM,data:rVjaOVtFFk1MdLKsOIHdC99GIpQWm1YfFHj5jmfIgiI=,iv:8ZyoRDDj8VWRruJE71U35u60kpPC55d6/buKzEQ3Bas=,tag:mIXbv5DUsHbBpybqDKnlpw==,type:str]
    DEFAULT_USER_PASSWORD: ENC[AES256_GCM,data:4lIO3n2+5wDowd4PRjMx/BIbtURas7F4mpsiSXUS9OA=,iv:ps8Q0uewZ2ca3WIbLI2KfkDKI5HRAfrwKWbefmDGYKE=,tag:iagObJst0Z+Cxmo3MkMRWA==,type:str]
sops:
    age:
        - recipient: age1lcl4x9eckuj7skyjq26h4e70dl2qvjec3saerxzunp8z7r28e3qsd0c8d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZDF5TVVBc3Z5cVpwT2c1
            WWt3dnYrRThaMmRUNGIvQ21iUmFuNm5UMTJVCkZmWlRtYWNxc0VVVFBnWXJkY1Bo
            TFRQRTdzTFJJSjJrVDdpajFWdVk3WGsKLS0tIDVFM3kvQU04VkpwOGZuaFVHTG43
            NzlpVkVKMVdOL0thOFI4Q2drMXVGM2sKFoctDhf3s/RruFfxNBEhTkcOtNYpzqRn
            zDvzwvX2qseWm3k83Ugee407HErDU8dfsP8/gjNnBYmk2/YCHz3iQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T09:59:52Z"
    mac: ENC[AES256_GCM,data:uJOlbb4fEfR/6zE26/AM3REZcc6BFnKe9oxw/bK2NSuyobUj3hgX1uZbGDsuhiguhoXAXCeSpqrCkjOE7NrpiNhFhLqfW5gjeHT23P3SvvFMyFzb1ujQWmyXtaOqVeNDRntSEWTZm4uiqq7O3VpAMgC2yemiHu69RtQpRTRu4lo=,iv:T06YIFZPzyb/4wzDUiFxIF6H4rbX4cQ7aBISdML5yd8=,tag:MxHiXrNEHLm16Ggv/IUmbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
