# Context Forge MCP Server Registration
# Auto-provisioning: The context-forge-init job automatically registers backend servers
# and creates virtual servers when the pod starts up.
#
# Architecture:
#   BACKEND SERVERS (sources)
#   ├── azure-go (HTTP)      → provides Azure tools
#   ├── groupme (SSE)        → provides GroupMe tools
#   └── clickup-native (SSE) → provides ClickUp tools
#
#   VIRTUAL SERVERS (what OpenWebUI sees)
#   ├── "azure mcp"    → bundles all Azure tools
#   └── "clickup mcp"  → bundles all ClickUp tools
#
# For GroupMe: Users authenticate per-user via Auth Registration tool

apiVersion: v1
kind: ConfigMap
metadata:
  name: context-forge-servers
  namespace: apps
data:
  # Documentation of MCP servers auto-provisioned
  # 
  # IMPORTANT: 
  # - Backend servers (azure-go, groupme, clickup-native) auto-registered via init job
  # - Virtual servers (azure mcp, clickup mcp) auto-created via init job
  # - Do NOT manually register - context-forge-init.yaml handles everything
  #
  servers.json: |
    {
      "servers": [
        {
          "name": "azure-go",
          "description": "Azure Cloud Management (Go)",
          "type": "http",
          "url": "http://azure-mcp-go.apps.svc.cluster.local:8080/mcp"
        },
        {
          "name": "groupme",
          "description": "GroupMe messaging (per-user auth)",
          "type": "sse",
          "url": "http://groupme-backend.apps.svc.cluster.local:5000/sse",
          "passthrough_headers": ["X-Authenticated-User"]
        },
        {
          "name": "clickup-native",
          "description": "ClickUp project management",
          "type": "sse", 
          "url": "http://clickup-mcp-server.apps.svc.cluster.local:5000/sse"
        },
        {
          "name": "ansible",
          "description": "Ansible Automation Platform / AWX",
          "type": "http",
          "url": "http://ansible-mcp-server.apps.svc.cluster.local:8080/mcp"
        }
      ],
      "virtual_servers": [
        {
          "name": "azure mcp",
          "description": "Azure cloud resource management tools",
          "backend_servers": ["azure-go"]
        },
        {
          "name": "clickup mcp",
          "description": "ClickUp task and project management tools",
          "backend_servers": ["clickup-native"]
        },
        {
          "name": "ansible mcp",
          "description": "Execute playbooks and manage automation jobs via Ansible AWX/AAP",
          "backend_servers": ["ansible"]
        }
      ]
    }
