apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupme-backend
  namespace: apps
  labels:
    app: groupme-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groupme-backend
  template:
    metadata:
      labels:
        app: groupme-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      imagePullSecrets:
      - name: regcred
      containers:
      - name: groupme-backend
        image: quazmoz/quazmoz:groupme
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:

        - name: MCP_TRANSPORT
          value: "streamable-http"
        - name: PORT
          value: "5000"
        # Multi-user mode settings (enables /auth/register endpoint)
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: groupme-mcp-secret
              key: ENCRYPTION_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: groupme-mcp-secret
              key: JWT_SECRET
        # Database for token storage (Postgres instead of Redis)
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://grafana_user:$(DB_PASSWORD)@postgres-service.apps.svc.cluster.local:5432/groupme_tokens?sslmode=disable"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: groupme-backend
  namespace: apps
spec:
  selector:
    app: groupme-backend
  ports:
  - port: 5000
    targetPort: 5000
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: groupme-backend-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  - host: groupme.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: groupme-backend
            port:
              number: 5000
