# This file defines the main OpenLiteSpeed WordPress application, its service, and ingress.
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      # Ensure WordPress runs on the node with the fast local storage
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      containers:
      - name: wordpress
        # Using the official OpenLiteSpeed WordPress image
        image: litespeedtech/openlitespeed-wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db-service"
        - name: WORDPRESS_DB_NAME
          value: "wordpress_db"
        - name: WORDPRESS_DB_USER
          value: "wordpress_user"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mariadb-password
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/vhosts/localhost/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-data-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: default
  annotations:
    # Homepage discovery annotations
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "WordPress POC"
    gethomepage.dev/group: "Websites"
    gethomepage.dev/icon: "wordpress.png"
spec:
  ingressClassName: nginx
  rules:
  - host: wordpress.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
