# This file defines the dedicated MariaDB database for your WordPress site.
apiVersion: v1
kind: Service
metadata:
  name: wordpress-db-service
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-db
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      # Ensure the database runs on the node with the fast local storage
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      containers:
      - name: mariadb
        image: mariadb:11.2 # Using a specific stable version
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          value: "wordpress_db"
        - name: MARIADB_USER
          value: "wordpress_user"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: mariadb-password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: wordpress-db-pvc

