# This PVC is for the WordPress application data (themes, plugins, uploads)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 25Gi
  # This explicitly binds this PVC to the correct PV
  volumeName: wordpress-data-pv
---
# This PVC is for the MariaDB database data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  # This explicitly binds this PVC to the correct PV
  volumeName: wordpress-db-pv

