# Grafana Alloy - OpenTelemetry Collector
# Receives OTLP metrics from OpenWebUI and exports to Prometheus
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: "0.9.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    alloy:
      configMap:
        create: true
        content: |
          // Receive OTLP data from OpenWebUI
          otelcol.receiver.otlp "default" {
            grpc {
              endpoint = "0.0.0.0:4317"
            }
            http {
              endpoint = "0.0.0.0:4318"
            }
            output {
              metrics = [otelcol.processor.batch.default.input]
              logs    = [otelcol.processor.batch.default.input]
              traces  = [otelcol.processor.batch.default.input]
            }
          }

          // Batch processor for efficiency
          otelcol.processor.batch "default" {
            output {
              metrics = [otelcol.exporter.prometheus.default.input]
              logs    = [otelcol.exporter.loki.default.input]
            }
          }

          // Export metrics to Prometheus
          otelcol.exporter.prometheus "default" {
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://prometheus-server.apps.svc.cluster.local/api/v1/write"
            }
          }

          // Export logs to Loki
          otelcol.exporter.loki "default" {
            forward_to = [loki.write.default.receiver]
          }

          // Write to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki.apps.svc.cluster.local:3100/loki/api/v1/push"
            }
          }

    # Expose OTLP ports
    service:
      type: ClusterIP

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
