# Grafana Alloy - OpenTelemetry Collector
# Receives OTLP metrics from OpenWebUI and exports to Prometheus
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: "0.9.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    alloy:
      configMap:
        create: true
        content: |
          // ========== KUBERNETES POD LOG SCRAPING ==========
          // Discover pods for log scraping
          discovery.kubernetes "pods" {
            role = "pod"
          }

          // Relabel pod logs with useful labels
          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets
            
            // Keep only running pods
            rule {
              source_labels = ["__meta_kubernetes_pod_phase"]
              regex         = "Pending|Succeeded|Failed|Unknown"
              action        = "drop"
            }
            
            // Set namespace label
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            
            // Set pod label
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            
            // Set app label from pod label if exists
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label  = "app"
            }
            
            // Set container label
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            
            // Set node label
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }
          }

          // Scrape pod logs
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.default.receiver]
          }

          // ========== OTEL RECEIVER (for OpenWebUI traces) ==========
          otelcol.receiver.otlp "default" {
            grpc {
              endpoint = "0.0.0.0:4317"
            }
            http {
              endpoint = "0.0.0.0:4318"
            }
            output {
              metrics = [otelcol.processor.batch.default.input]
              logs    = [otelcol.processor.batch.default.input]
              traces  = [otelcol.processor.batch.default.input]
            }
          }

          // Batch processor for efficiency
          otelcol.processor.batch "default" {
            output {
              metrics = [otelcol.exporter.prometheus.default.input]
              logs    = [otelcol.exporter.loki.default.input]
              traces  = [otelcol.exporter.otlp.phoenix.input]
            }
          }

          // Export metrics to Prometheus
          otelcol.exporter.prometheus "default" {
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://prometheus-server.apps.svc.cluster.local/api/v1/write"
            }
          }

          // Export OTEL logs to Loki
          otelcol.exporter.loki "default" {
            forward_to = [loki.write.default.receiver]
          }

          // Export traces to Phoenix (LLM Observability)
          otelcol.exporter.otlp "phoenix" {
            client {
              endpoint = "phoenix.apps.svc.cluster.local:4317"
              tls {
                insecure = true
              }
            }
          }

          // Write to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki.apps.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
      # Extra ports for OTLP receivers
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
