# Postgres Init Scripts ConfigMap
# Creates databases on first startup
# All databases use the default 'postgres' superuser for access
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: apps
data:
  01-create-databases.sql: |
    -- All databases are owned by the default 'postgres' superuser.
    -- No additional users are created; applications connect as 'postgres'.
    -- Password is managed via the postgres-credentials K8s Secret.

    CREATE DATABASE grafana_db;
    CREATE DATABASE authentik;
    CREATE DATABASE n8n;
    CREATE DATABASE openwebui_db;
    CREATE DATABASE freshrss;
    CREATE DATABASE coder;
    CREATE DATABASE langfuse;
    CREATE DATABASE azure_mcp_go;
    CREATE DATABASE context_forge;
    CREATE DATABASE groupme_tokens;
    CREATE DATABASE phoenix;

