# TODO: This secret is insecure and stores passwords in plain text in Git.
# It should be encrypted with SOPS for any real-world use.
apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: apps
stringData:
    #ENC[AES256_GCM,data:28TmuS+gbf1cnKNaxjJGq5uSKOUAYfAfmoM7hjnsILYM4I6zVGUWkI/b68lGMDENoGnb90M=,iv:AyQBkj7GFdnyRAGDwWmB67cZ4NV4YttYl1JbQBu5l8Y=,tag:A4KMgdn2K17AwwV9T1Lp2Q==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ozYXD3LP+0s4vsfaS1Y9pSfeuZ7L,iv:u3XMECLgGzFvawGbs3dtg0y1F0xrUE7RJGjwbOqDOpM=,tag:aHK6n0NOY/5/qpfiqVqV/A==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUk5NYmlQNEl4V1pxbE5E
            aDduYjFxN1d6Ykxrc1p5S1pzQzVOcHBIVVJZCmNaM1dVWUdCdVF0VTRyNm12NTIx
            ZDc3WjZJNUdQYlJheE9QTStJQjE3VGMKLS0tIGV2dWlvRjRJUGowTGxKQmJNanlr
            d3JqV3dYaG9JTVlkZjlZOU5CS3Y4T1UK9DrO6xZey162PgRfkWMaLoO2tIyWUR64
            RgmwSwo/mdVlAH8yMTi808slxsbUbbY9Hwx8OfZb8og1R2IMUxJEaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:MWHr2jcZEDpv9F5Z6xKjgpfp2Fj+WIoNteA82SP0gBFXfNUCNtJmnSglA2pNFpnoMCxWa+B1kcRTaqlPrlL0cUBQ6t620jSvxMyoly2IQ4pQuQKeFe2gjv708vZmPiMr3tpljrUso1a6CccimL4lY0f9jTZOH+q1lbgF/E+r1l4=,iv:ywipyA2NQfhGGk7ntp1fdnJZWO+j/KQ6ZpS6/shRyf8=,tag:IRRiJdDtNFgxy8AOuapcBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
