# Nightly Postgres backup CronJob
# Runs at 2 AM EST (7 AM UTC) and stores compressed backups on USB storage
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: apps
spec:
  schedule: "0 7 * * *"  # 7 AM UTC = 2 AM EST
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          # Run on raspberrypi3 where USB storage is mounted
          nodeSelector:
            kubernetes.io/hostname: raspberrypi3
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: postgres:15
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              value: "postgres-service"
            - name: PGUSER
              value: "grafana_user"
            - name: PGDATABASE
              value: "grafana_db"
            command:
            - /bin/bash
            - -c
            - |
              set -e
              BACKUP_DIR="/backups/postgres"
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_FILE="${BACKUP_DIR}/postgres_backup_${TIMESTAMP}.sql.gz"
              
              echo "Starting Postgres backup at $(date)"
              mkdir -p ${BACKUP_DIR}
              
              # Create compressed backup
              pg_dump -h ${PGHOST} -U ${PGUSER} ${PGDATABASE} | gzip > ${BACKUP_FILE}
              
              if [ $? -eq 0 ]; then
                echo "Backup successful: ${BACKUP_FILE}"
                ls -lh ${BACKUP_FILE}
                
                # Cleanup old backups (keep last 7 days)
                echo "Cleaning up backups older than 7 days..."
                find ${BACKUP_DIR} -name "postgres_backup_*.sql.gz" -mtime +7 -delete
                
                echo "Current backups:"
                ls -lah ${BACKUP_DIR}
              else
                echo "Backup failed!"
                exit 1
              fi
              
              echo "Backup completed at $(date)"
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
