apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  # This must match the storage class of our PV
  storageClassName: local-storage
  
  # This must match the access mode of our PV
  accessModes:
    - ReadWriteOnce
    
  # This requests storage, and Kubernetes will bind it to a PV
  # that can satisfy this request (e.g., our 10Gi postgres-local-pv).
  resources:
    requests:
      storage: 10Gi
