# TODO: This deployment relies on an insecure plain-text secret for credentials.

# --- Internal Service for Postgres ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: apps
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
# Also expose as 'postgres' for easier service discovery
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: apps
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
# --- The main Postgres Deployment (as a StatefulSet) ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # The nodeSelector has been removed from here.
      # Scheduling is now driven by the nodeAffinity of the PersistentVolume.
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        # Use standard postgres superuser
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        # Default database
        - name: POSTGRES_DB
          value: "postgres"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
