apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: default
stringData:
    #ENC[AES256_GCM,data:0pmv7hykl8yqePunosL0wXwwW8YS1Dy2e2D2jQA5Ra92Lk0Zt5wnKOwNzQ+RyJHB,iv:hYnpVHLHHkArnG17BLSAxq3WKe1CcgR4LglT58A8e3g=,tag:iW8fBpiKwgbErYE2IAUGNQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ifafYPJW3tEqX4g7oZa/eSzc,iv:jdXpyPH5HGiLbfqpD2Ms7h9h8E2Evq9h/At+8tZGIXs=,tag:TUT8Ina95wxiT1xY55Ki3A==,type:str]
sops:
    lastmodified: "2025-07-15T12:00:38Z"
    mac: ENC[AES256_GCM,data:V0s5cAKnq2GAfKd0LGCYfMMkyqrBk1o/s1dognkV9eTlFLtRhSAee4LZFdEDlaCWVqwFoZ7l8PxjXrWzl5cV9/y7vqG71lQmSwVhOm3S3Uxsd7ZuipKZ9MLfF0tnk9WfYJ6jxxSF/lmHZwCJQE7h5wjv6oO0Kryrfb5iXtlr2wg=,iv:Etz0gy91TVmgSlSK4HtubjaB3B9I9X6ah83H2b0EB28=,tag:8vMrihm9rAhHCIF4Rxs2kw==,type:str]
    pgp:
        - created_at: "2025-07-15T12:00:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3AzYX4areuVARAAgbu1+GebCeYMPRzoZ0UZdbaOzRUVLJ+Hvok2bgQk/psi
            LrQnhO2NtVt3mhVJg7DgS86A0Na2VchCxG9Lxq+h4fvdnzjH7F+OeBrPLdYWTznn
            nlSG7xAkclVkNrXlPiIYMzxMoSwgTtAX99hcwLHWVVsy/4I6zxzEQCjutNAAPa+q
            sdnL4mCuT6XbZ7zGEsIKar8dBTMOsxVcs6xPwDOhwRv3ioDDzcWj5Lh0vtVd2ZRQ
            5KLTh6rmI2tyZAGfdMsBQz7pxF0GZ5QitVG7n16FEQZOlNgOi1FuGdnXx9JeHmqe
            0/Nv9/fShGXqPszVGTRqxbd5WAdIcntGIr5HTQHrwRNEJMzFBclG8zVKxaJcTwby
            qqmt0VvlODZj+SU/0RJ7tn25UBR7KXu6WLupQwb42Gm3LvRBlnP/VmPuyMaRV8V3
            DTlYEuQIukqR6+YSrDVn+IrvT4ZXWnD6T6vX3lG+bWDNu8AbumdlWWdgD9we9amv
            nCdCB0sRlCp12S/LgNjbJy3c2/TWoEuJmpLLYvqOe7NSDP8gMmtNArGhs+2m0ARB
            LtrAWeMILi6JjdPF0XIczMzTnv08zISBSgRIxiUVXsZqPTizh8qiq+moh5d/i2hv
            cCsIg4hZlF1t1sLCp+9Ekk2ZALOGaiSne53SEp3iAy78i8MpAVDjiQdfRsoOgA7S
            XgH1NHgAELhkcTewSzSkSrgylmeNMu/hA/kmctMSXmirEe4gG7CdfyAglaCJnnsx
            MDWM2VdAw/qqo3kn0T87isT9lXtAQBT5GqWhlSmM6z4fCLJHQnegvchcil4nkco=
            =Chvq
            -----END PGP MESSAGE-----
          fp: 793DC6A1A31DAAA0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
