apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: usb-slow-storage
  volumeName: usb-logs-1-pv
  resources:
    requests:
      storage: 7Gi
  selector:
    matchLabels:
      type: usb-slow
