# Jupyter Notebook PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  namespace: apps
  labels:
    app: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: jupyter-local-pv
  resources:
    requests:
      storage: 5Gi
