apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.0.10"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  values:
    # Use persistence to store workflows and credentials
    persistence:
      enabled: true
      storageClass: "local-storage"
      size: 15Gi

    # Set your timezone
    env:
      TZ: "America/New_York"