apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/n8n
      sourceRef:
        kind: GitRepository
        name: n8n-chart-source
        namespace: flux-system
      interval: 1m
  values:
    # This is the corrected structure for persistence in this chart
    n8n:
      # We are not using postgres, so these are false
      postgresql:
        enabled: false
      database:
        type: "sqlite"

      # This enables the persistent volume for the data
      persistence:
        enabled: true
        # This must match the name of the PVC that will be created
        # and that will bind to our PV.
        name: n8n-data
        storageClass: "local-storage"
        size: 15Gi
        accessMode: ReadWriteOnce

    env:
      TZ: "America/New_York"