apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: n8n-chart-source
  namespace: flux-system
spec:
  interval: 10m
  url: oci://8gears.container-registry.com/library
  ref:
    tag: 1.0.0
  provider: generic
