apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeName: freshrss-local-pv
