apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
spec:
  template:
    spec:
      containers:
        - name: kube-flannel
          args:
            - --iface-can-reach=192.168.1.1