apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-agent-pvc.yaml
  - hermes-agent-service.yaml
  - hermes-agent-ingress.yaml
  - hermes-agent-configmap.yaml
  - hermes-agent-deployment.yaml
  - hermes-agent-credentials.secret.enc.yaml
