# Paperclip secrets (SOPS-encrypted). Edit: sops apps/base/paperclip/paperclip-secrets.secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets
    namespace: apps
type: Opaque
stringData:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:3aey5YrDWUqWZEUP61hAJG1BsPLMkYcC1XT8XV+ZziOTA8B+OfvNddxRXEgw5p2XazeEfM4=,iv:taQYr4bgprnwXrPOmNZsDwT7wfcpCxlwUo96+NJyTpA=,tag:7P6XtcZDYA76DEEl2/58gQ==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:osUK8M+krTqDjDJdm82gOKVHnx52OgCU5roBmT52g+c=,iv:BsSFl4c2yZmXdh/Jpg8F8688z6+f7okUsPx+x22sCbE=,tag:F8p0bx4MgT/Jing2EU9qfQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:w0FjTcj67KsSCgF58oLUfOyWPJlqMzpDaDR3gA2cqtz/UEo6agBjYUoqHApfzNL4zUgfft1285X2DwneEApwxg==,iv:/20nbNonG4yF0bZ+tXzn+MzuqSnmIJlsIJ7gLAM+4Us=,tag:8+Nn4Cvjvm+uZASiozbTDA==,type:str]
    PAPERCLIP_TOOL_ACTION_SIGNING_SECRET: ENC[AES256_GCM,data:oGqSnDWBmklaEj9dv9K34VMt39t8Y28a2AGLm5acvI26xL+XUMTQdBjxWingpmOOVvd8DCBANjCVKCTGIusv2Q==,iv:dxfFSCvHcrw+YiY0dddeyjRJ6Ic1ylxZQtbRHgPwhiw=,tag:tv2xgVdDOdZLJmkxWY6q7Q==,type:str]
    OLLAMA_API_KEY: ENC[AES256_GCM,data:JeTU91wPng2mZf6XdxJS4lln0C7vLW1ixxPW7msBVlyG+hkEULUpf7hHiggM5+7SJK4VserCj2zq,iv:HCOKH/nSj74y3+tC2Q5gXJ/e4vyulviT5aIqwwGMRlc=,tag:SzTxT6++ebBzb7iUuWxTAw==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTVQyRkY2L0xydUNGa0V3
            ZGVKbFg1SzZ1NjNoVUNNcWN0YnlGdzNDdEdRCkZnZWdKSmxnZTlrNGhTandwVXBZ
            M1pYaTNiUVFuSmowUDRWTFFOQTZGamsKLS0tIC84N0FKSjdRZW9BWWNFbGtFa1E5
            OFFORE91NjB2OHlEeTRGUmFZSGE0elkKvA5qFDD1t3zc0K0JUX3m3GUZFPipbbiJ
            xVaWJK+8h2ga2HuN9X2LEnIQfh83xR6w+xPudcngiyGnTnYy63soGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T11:32:23Z"
    mac: ENC[AES256_GCM,data:oDOMFAp+T9wFE6zf3Q84x52mPe/xq2Wn4OG8N/e0GiopY7g7LcMBI4zngqyg4WczyU2ALY80Y+ivfXDmz0yCR+G+w7Lo4998nMGvK+wo15miXAl/kNG2PknrXjcBQ6c1KQ5ZKr2hjAaacN2jXhcjnE6cQAnQ7e+IJ31kKWEzo58=,iv:nfdt8OnT+nh4s6LQKSPmaRx2E2neHIZvNUYpgMV7EOQ=,tag:NpMaMDFYOY5lZ8rNfnX2Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
