apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanium-mcp-server
  namespace: apps
  labels:
    app: tanium-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanium-mcp-server
  template:
    metadata:
      labels:
        app: tanium-mcp-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      imagePullSecrets:
      - name: regcred
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: tanium-mcp-server
        image: quazmoz/quazmoz:tanium
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: CACHE_TTL
          value: "300"
        - name: MCP_TRANSPORT
          value: "sse"
        - name: TANIUM_API_URL
          valueFrom:
            secretKeyRef:
              name: tanium-mcp-secret
              key: TANIUM_API_URL
        - name: TANIUM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: tanium-mcp-secret
              key: TANIUM_API_TOKEN
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tanium-mcp-server
  namespace: apps
  labels:
    app: tanium-mcp-server
spec:
  type: ClusterIP
  selector:
    app: tanium-mcp-server
  ports:
  - port: 5000
    targetPort: 5000
    name: http
