apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - n8n-sandbox-pv.yaml
  - n8n-sandbox-auth.secret.enc.yaml
  - n8n-sandbox-api-registration-tls.secret.enc.yaml
  - n8n-sandbox-api-control-client-tls.secret.enc.yaml
  - n8n-sandbox-runner-registration-tls.secret.enc.yaml
  - n8n-sandbox-runner-control-tls.secret.enc.yaml
  - helm-release.yaml
