apiVersion: v1
data:
    api-keys: ENC[AES256_GCM,data:j91CgAHgHM7kjC/36KoB0U/7pf02hV0FlltaEmZSzmaWuLGmZUTSU4cGyY4b6DAsPhVtrxbzCN2Gv1DJHpNhPQjKDsdicBt/cmEXNb65P9s200tQXTfiwg==,iv:yRUoXFBrMElYe7DmfIBXtOC89wBqPI23XT/jU7GR0Ck=,tag:KlU9hGWkvEQJPoboQeDtyg==,type:str]
    runner-api-key: ENC[AES256_GCM,data:ES+9zFnf/CwzpnETeY5AkhoZzpgzx/waCTdRywHaIOuZ2CjaFNo+h2EvirRqdx55Br9vhtNQsouJ0RFBmUVdFtc4mlhM5cETh8EJ8CWEKgnqcsRNNPT9nw==,iv:gDl951YassW+0CbDT1Fpr1RUhzgjAGH8D+QEsISKzzM=,tag:Rv/vB+74pRhWCDfhP/1PbQ==,type:str]
    runner-api-keys: ENC[AES256_GCM,data:a67wTTPr9gCjGuHIKOpU1uoAe/FRFn3BVwl9oXASx9Dg12n0e9KvMbHK1G6qfIxlQJ9sm6mqp14OLZxJ0dVeY16v9vYsiYxvdah5jsLc24T4pvLPsRSKcw==,iv:2/xqP4kbppQPk6dQ47jXAfyTcPcx7naWtbJLa4+w/Jw=,tag:yqu7HAwkM45WfQrtLvQyNw==,type:str]
    runner-registration-token: ENC[AES256_GCM,data:Eg00A8jQdUGQFOXfBUKOMZY7ca2HAxPnI7PvRiOf5y2zIdNHz1XQw5GNf4Ft9YrwUFkkxDW8W05vZ7wvqBHUYyiHfGnLidwXH11i01/8jdETN9jYpaZGZg==,iv:ZciDgCNavhWAGpP2OAlAfYtpiMVP18L2rPvYM2y00pI=,tag:VFzsrwgWLoA3jAQViCXSDw==,type:str]
kind: Secret
metadata:
    name: n8n-sandbox-auth
    namespace: apps
sops:
    age:
        - recipient: age1lcl4x9eckuj7skyjq26h4e70dl2qvjec3saerxzunp8z7r28e3qsd0c8d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcExaTFZvUy9yQUh1NVhT
            bTdzVlErajQwaUJFTkNxYWVzQTRjTDNvTzE0ClJ2OU9PVnYzOVRGTWRONzVnbFlt
            STlkcmFNOFBDM1pjTFRPcmJJK1NWb2sKLS0tIHZmSk5aL0xoVUJ2QnlGUXJTYklZ
            dUo4bnBSN0tHdkdkaWpQeTQxajRKaG8Kpn9HXjf9VK0A2f8LutldgtFVSUmjSeqx
            ZZV03nlXxRc5Wylu966pNcZI2Q3Ofo/Fmf0N0Ut7Mtg05p78MN06Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-24T19:59:28Z"
    mac: ENC[AES256_GCM,data:lOQEZ7xj/C3PR8oYPyvgl7O5vaWK2if13ujWRx3ST656Ndkx8Obl25YeVLJuA1UZylfcNfO6SxVXQHEARfRhwKSoAffQFxsqBzv3U4kJ7JoNshBNrj84BiLkDVZ76lpVOjNEaPDwYu9ys8q8mJ+s+FJXEO9JG6UexEdN1ONQUMw=,iv:RYGOGHyvzOI2hxbTMgJAFNUJ5Sf5f3+gIPBCY17UgZE=,tag:kG94cb5Eh29yLBvOHCkOTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
