apiVersion: v1
data:
    api-keys: ENC[AES256_GCM,data:r08XL6gp6LWGx3o+jEajI6YYfawmcYr5A0hjf85Gr4L/gxaX9gm45wtV3sHLJeMxC2Hf4nr/I+xY9QERSuE2/LXgJRte0t1m/JRVouTXUW5YeUQJjKUrtg==,iv:yRUoXFBrMElYe7DmfIBXtOC89wBqPI23XT/jU7GR0Ck=,tag:KfL9qljAVyR5maexTAkO2A==,type:str]
    runner-api-key: ENC[AES256_GCM,data:6SZFONTDrrhoLcbJTyT1GN3g4rLHD6BNjcDngSQAPfnVrujRBcWZpvz8ULwnU4o5m3DD1dtwodMWXyOSYvPaUm7ZLRtOeFfAw0TFGcI/9x7dx9yP90mRYA==,iv:gDl951YassW+0CbDT1Fpr1RUhzgjAGH8D+QEsISKzzM=,tag:AFLycm/WtIsnintd70Tdvw==,type:str]
    runner-api-keys: ENC[AES256_GCM,data:2Mo62BPiGS6KJhASJJNQIZz8Lo4hWcKeh4fYfTaruY+CNyiIufXf7J+ha6sj8ADSqUlhIwNpUMW7V9mMZ4CqIGba0Ds4vFrK9rEuVqXiMlsk3ixfNXM4Vw==,iv:2/xqP4kbppQPk6dQ47jXAfyTcPcx7naWtbJLa4+w/Jw=,tag:OGW1jDuOtPZ5ILcHydK9dQ==,type:str]
    runner-registration-token: ENC[AES256_GCM,data:o1KxFx225uXY01teJzaUZUlipzGH6Mr0vvEWhsaLVqwkqJOwubqqZxGlvUoBRZHrP/Bbd0GdpZ6am5BaNSFmlmE0ERyh0xwDYJGRZwBXu+ONCDjWw5wcCA==,iv:ZciDgCNavhWAGpP2OAlAfYtpiMVP18L2rPvYM2y00pI=,tag:FmKHRW8iJkJg0H7Z1H1t1w==,type:str]
kind: Secret
metadata:
    name: n8n-sandbox-auth
    namespace: apps
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UFBUMVo5TCs2MjJmRTZK
            dm9vOWZneVNydzFZUW5vL1ZKOUdLaTUyQlhjCjV1VnFkbUNsSS9MUmNVQlRzRDlR
            R2Q3NzFtUVIvSzJnK0RNOGRCa3Bmc3MKLS0tIHRldlJNdWFhY1R0VDU4UWtrR3J3
            VkVxMFNOeWpaL3hYY2JyYnNza09SVWMKJcIUG3zNVdkbvUrxmxKULMc3LHKzNSz6
            1OLgAsZBWrlXhA6bSsqAwcpMIG7Hi/rEFmc0E+1iFio/naSb9Nz8XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:9Sk0zuSF2qJ/Ruo1BhsGO9A8PePk2zD2p/rxXJQZKkpsdrs1xfyBp9y4/mhxgMH7P5s5ioIfCseszr0gYx2RGY308TZHZBLYmiXv2+eagCiw8gBRfqorKxlKJAnXpPKP4d8IVknr5AaYgRe295PoMtl8oq6VgbY5BGkhjstQEN0=,iv:WlZG4N1CYad+Lz3JQ5HC5A4PVhqiFNgZzr2zaCJzxxI=,tag:HhTzt5FbWALuUHhjIXOx3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
