apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      # Using a known stable version range from the Bitnami repository
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    # By removing the 'image' override, we will use the chart's default,
    # stable, and optimized WordPress+Apache container.

    # Configure the MariaDB sub-chart that comes packaged with the WordPress chart
    mariadb:
      enabled: true
      # Configure persistence for the database
      primary:
        persistence:
          enabled: true
          storageClass: "local-storage"
          # This must match the wordpress-db-pv size we defined in storage.yaml
          size: 10Gi
      # Set credentials for the database
      # IMPORTANT: Change these to secure, random passwords!
      auth:
        rootPassword: "YourDBRootPassword!"
        database: "wordpress_db"
        username: "wordpress_user"
        password: "YourDBUserPassword!"

    # Configure persistence for the WordPress application itself (themes, plugins, uploads)
    persistence:
      enabled: true
      storageClass: "local-storage"
      # This must match the wordpress-data-pv size we defined in storage.yaml
      size: 25Gi

    # Configure the Ingress to expose the site to your network
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "wordpress.k8s.local"
      path: /
      pathType: Prefix
      annotations:
        # Homepage discovery annotations so your dashboard finds this site automatically
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "WordPress Site"
        gethomepage.dev/group: "Websites"
        gethomepage.dev/icon: "wordpress.png"

