# This is the HelmRelease for Jenkins.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: "4.9.x" # Use a recent, stable version range
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      interval: 1m
  values:
    controller:
      # We disable the chart's built-in persistence, as we are creating our own PVC manually.
      persistence:
        enabled: false

      # We manually tell the Jenkins pod to mount our custom PVC.
      additionalVolumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins
      
      additionalVolumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

      # Add some essential plugins to install on first boot
      installPlugins:
        - kubernetes:4186.v1821a_19672f2
        - workflow-aggregator:596.v802b_b_4fd69b_d
        - git:5.2.2
        - configuration-as-code:1782.v9b_3936650762

      # Define resource requests and limits for the Jenkins controller pod
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
