# This PVC is the link between our application and our physical storage.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: apps
spec:
  # This must match the storage class of our PV
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # This creates an explicit 1-to-1 binding to the correct PV,
  # ensuring Jenkins always gets its dedicated storage.
  volumeName: jenkins-local-pv
