apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: apps
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 33  # Changed from 82 to 33
          containers:
          - name: nextcloud-cron
            image: nextcloud:28.0.2-apache  # Same version as main container
            command:
            - /bin/sh
            - -c
            - |
              # Wait for Nextcloud to be ready
              echo "Waiting for Nextcloud to be ready..."
              for i in {1..30}; do
                if [ -f /var/www/html/config/config.php ]; then
                  echo "Nextcloud config found, running cron..."
                  php -f /var/www/html/cron.php
                  exit $?
                fi
                echo "Waiting for Nextcloud config ($i/30)..."
                sleep 10
              done
              echo "Nextcloud config not found after waiting. Exiting."
              exit 1
            volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          restartPolicy: Never
          volumes:
          - name: nextcloud-data
            persistentVolumeClaim:
              claimName: nextcloud-data-pvc
