apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: apps
  labels:
    app: nextcloud
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nextcloud
