apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: default
data:
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.k8s.local
  NEXTCLOUD_DATA_DIR: /var/www/html/data
  PHP_MEMORY_LIMIT: 512M
  PHP_UPLOAD_LIMIT: 10G
