apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  settings.yaml: |
    title: Homelab Dashboard
    background: https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?q=80&w=2693&auto=format&fit=crop
    providers:
      kubernetes:
        cluster:
          inCluster: true

  services.yaml: |
    - "Cluster Tools":
        - "Kubernetes Dashboard":
            href: https://dashboard.k8s.local
            icon: kubernetes-dashboard.png
            description: Cluster management UI

    - "Monitoring":
        - "Grafana":
            href: http://grafana.k8s.local
            icon: grafana.png
            description: Metrics and dashboards
        - "Prometheus":
            href: http://prometheus.k8s.local
            icon: prometheus.png
            description: Time-series database

    - "Media":
        - "Plex":
            href: http://192.168.1.240:32400/web
            icon: plex.png
            description: Media Server

  widgets.yaml: |
    - resources:
        label: "Node Resources"
        kubernetes:
          k8s_node: "debiank8snode"
    - search:
        provider: duckduckgo
        target: _blank

  bookmarks.yaml: |
    - "Favorites":
        - "GitHub":
            href: "https://github.com/quazmoz"