apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      version: "1.2.x" # Use a recent, stable version range
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
      interval: 1m
  values:
    # Tell the chart to get its config from our ConfigMap
    configMap:
      # The name must match the ConfigMap we created above
      name: "homepage-config"