# --- 1. ServiceAccount for Homepage to talk to the API Server ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: apps
---
# --- 2. The ConfigMap containing all your dashboard settings ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: apps
data:
  settings.yaml: |
    title: Quinn's Homelab
    favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/kubernetes.png
    background:
      image: https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1920
      blur: sm
      opacity: 15
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    hideVersion: true
    useEqualHeights: true
    layout:
      AI & LLM:
        icon: mdi-brain
        style: row
        columns: 4
      MCP Tools:
        icon: mdi-api
        style: row
        columns: 5
      DevOps:
        icon: mdi-infinity
        style: row
        columns: 4
      Operations:
        icon: mdi-monitor-dashboard
        style: row
        columns: 6
      Portfolio:
        icon: mdi-account-star
        style: row
        columns: 4

  services.yaml: |-
    - AI & LLM:
        - OpenWebUI:
            href: http://openwebui.k8s.local
            icon: si-openai
            description: LLM Chat Interface
            siteMonitor: http://openwebui.apps.svc.cluster.local:8080
            statusStyle: dot
        - LLaMA Factory:
            href: http://llamafactory.k8s.local
            icon: mdi-tune-vertical
            description: LLM Fine-Tuning
            siteMonitor: http://llamafactory.apps.svc.cluster.local:7860/
            statusStyle: dot
        - Qdrant:
            href: http://qdrant.k8s.local/dashboard
            icon: mdi-vector-combine
            description: Vector Database
            siteMonitor: http://qdrant.apps.svc.cluster.local:6333
            statusStyle: dot
        - FreshRSS:
            href: http://freshrss.k8s.local
            icon: si-rss
            description: RSS Intelligence
            siteMonitor: http://freshrss.apps.svc.cluster.local:80
            statusStyle: dot
        - LibreChat:
            href: http://librechat.k8s.local
            icon: mdi-chat-processing
            description: Alt LLM Interface
            siteMonitor: http://librechat.apps.svc.cluster.local:3080
            statusStyle: dot

    - MCP Tools:
        - Azure:
            href: http://mcpo.k8s.local/azure/docs
            icon: azure
            description: Cloud Management
            siteMonitor: http://mcpo.apps.svc.cluster.local:8000/azure/docs
            statusStyle: dot
        - Kubernetes:
            href: http://mcpo.k8s.local/kubernetes/docs
            icon: kubernetes
            description: Cluster Ops
            statusStyle: dot
        - Prometheus:
            href: http://mcpo.k8s.local/prometheus/docs
            icon: prometheus.png
            description: Metrics API
            statusStyle: dot
        - PostgreSQL:
            href: http://mcpo.k8s.local/postgres/docs
            icon: si-postgresql
            description: Database API
            statusStyle: dot
        - n8n:
            href: http://mcpo.k8s.local/n8n/docs
            icon: n8n.png
            description: Workflows API
            statusStyle: dot
        - ClickUp:
            href: http://mcpo.k8s.local/clickup/docs
            icon: mdi-clipboard-check
            description: Project Mgmt
            statusStyle: dot
        - FreshRSS:
            href: http://mcpo.k8s.local/freshrss/docs
            icon: si-rss
            description: RSS API
            statusStyle: dot
        - GroupMe:
            href: http://mcpo.k8s.local/groupme/docs
            icon: mdi-forum
            description: Messaging API
            statusStyle: dot
        - Tanium:
            href: http://mcpo.k8s.local/tanium/docs
            icon: mdi-shield-lock
            description: Security API
            statusStyle: dot

    - DevOps:
        - Jenkins:
            href: http://jenkins.k8s.local
            icon: jenkins.png
            description: CI/CD Pipelines
            siteMonitor: http://jenkins.apps.svc.cluster.local:8080
            statusStyle: dot
        - n8n:
            href: http://n8n.k8s.local
            icon: n8n.png
            description: Workflow Automation
            siteMonitor: http://n8n.apps.svc.cluster.local:5678
            statusStyle: dot
        - Grafana:
            href: http://grafana.k8s.local
            icon: grafana.png
            description: Dashboards
            siteMonitor: http://grafana.apps.svc.cluster.local:80
            statusStyle: dot
        - Prometheus:
            href: http://prometheus.k8s.local
            icon: prometheus.png
            description: Metrics
            siteMonitor: http://prometheus-server.apps.svc.cluster.local:80
            statusStyle: dot
            widget:
              type: prometheus
              url: http://prometheus-server.apps.svc.cluster.local
        - Uptime Kuma:
            href: http://status.k8s.local
            icon: uptime-kuma
            description: Status Page
            siteMonitor: http://uptime-kuma.apps.svc.cluster.local:3001
            statusStyle: dot
        - Loki:
            href: http://grafana.k8s.local/explore?orgId=1&left=%7B%22datasource%22:%22loki%22%7D
            icon: loki
            description: Log Aggregation
            siteMonitor: http://loki.apps.svc.cluster.local:3100/ready
            statusStyle: dot
        - Authentik:
            href: http://auth.k8s.local
            icon: authentik
            description: Identity Provider
            siteMonitor: http://authentik-server.apps.svc.cluster.local:80
            statusStyle: dot

    - Operations:
        - pgAdmin:
            href: http://pgadmin.k8s.local
            icon: si-postgresql
            description: PostgreSQL Admin
            siteMonitor: http://pgadmin.apps.svc.cluster.local:80
            statusStyle: dot
        - RedisInsight:
            href: http://redisinsight.k8s.local
            icon: si-redis
            description: Redis Admin
            siteMonitor: http://redis-insight.apps.svc.cluster.local:5540
            statusStyle: dot
        - PostgreSQL:
            icon: si-postgresql
            description: Database
            statusStyle: dot
        - Redis:
            icon: si-redis
            description: Cache
            statusStyle: dot
        - Ingress NGINX:
            icon: nginx.png
            description: Ingress
            statusStyle: dot
        - MetalLB:
            icon: mdi-lan-connect
            description: Load Balancer
            statusStyle: dot

    - Portfolio:
        - quinnfavo.com:
            href: https://quinnfavo.com
            icon: mdi-web
            description: Personal Website
            siteMonitor: https://quinnfavo.com
            statusStyle: dot
        - Profile:
            href: https://profile.quinnfavo.com
            icon: mdi-card-account-details
            description: Professional Profile
            siteMonitor: https://profile.quinnfavo.com
            statusStyle: dot
        - AI Portfolio:
            href: https://ai.quinnfavo.com
            icon: mdi-head-lightbulb
            description: AI Projects
            siteMonitor: https://ai.quinnfavo.com
            statusStyle: dot
        - Universe:
            href: https://universe.quinnfavo.com
            icon: mdi-creation
            description: Universe Project
            siteMonitor: https://universe.quinnfavo.com
            statusStyle: dot
        - DevOps Toolkit:
            href: https://devopstoolkit.quinnfavo.com
            icon: mdi-wrench-cog
            description: DevOps Resources
            siteMonitor: https://devopstoolkit.quinnfavo.com
            statusStyle: dot
        - GitHub:
            href: https://github.com/quazmoz
            icon: si-github
            description: Code Repositories
            statusStyle: dot
        - LinkedIn:
            href: https://www.linkedin.com/in/quinnfavo/
            icon: si-linkedin
            description: Professional Network
            statusStyle: dot

  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
        focus: false
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h12
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "k8s-homelab"
        nodes:
          show: true
          cpu: true
          memory: true

  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true
    namespaces:
      show: true
      displayedNamespaces:
        - apps
        - kube-system
  custom.css: |
    /* Glassmorphism effect for service cards */
    .service {
      backdrop-filter: blur(12px) !important;
      -webkit-backdrop-filter: blur(12px) !important;
      background: rgba(30, 41, 59, 0.65) !important;
      border: 1px solid rgba(255, 255, 255, 0.08) !important;
      border-radius: 16px !important;
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;
    }
    
    .service:hover {
      transform: translateY(-4px) !important;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4) !important;
      border-color: rgba(255, 255, 255, 0.15) !important;
      background: rgba(30, 41, 59, 0.8) !important;
    }
    
    /* Smooth transitions for all interactive elements */
    .bookmark, .widget {
      transition: all 0.2s ease !important;
    }
    
    .bookmark:hover {
      transform: scale(1.05) !important;
    }
    
    /* Status dot glow effect */
    .status-dot {
      box-shadow: 0 0 8px currentColor !important;
    }
    
    /* Group headers styling */
    .group-header {
      text-transform: uppercase !important;
      letter-spacing: 0.1em !important;
      font-weight: 600 !important;
    }
    
    /* Subtle gradient on search bar */
    input[type="text"] {
      background: linear-gradient(135deg, rgba(39, 39, 42, 0.8), rgba(24, 24, 27, 0.9)) !important;
      border: 1px solid rgba(255, 255, 255, 0.1) !important;
      border-radius: 12px !important;
    }
    
    /* Widget cards */
    .widget-container {
      backdrop-filter: blur(8px) !important;
      background: rgba(39, 39, 42, 0.6) !important;
      border-radius: 12px !important;
    }
  custom.js: ""
---
# --- 3. RBAC rules to allow Homepage to read Ingresses, nodes, pods, etc. ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: apps
---
# --- 4. The internal Service to expose the pod ---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
---
# --- 5. The PVC for Homepage config ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: homepage-local-pv
  resources:
    requests:
      storage: 1Gi
---
# --- 6. The Deployment to run the Homepage application ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: dashboard
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
      annotations:
        # Force pod restart when ConfigMap changes
        checksum/config: "v13-librechat"
    spec:
      serviceAccountName: homepage
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      # Init container copies config from ConfigMap to PVC on first run
      initContainers:
        - name: init-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              # Always update config from ConfigMap
              echo "Updating config files from ConfigMap..."
              cp /configmap/* /config/
              echo "Config files updated."
          volumeMounts:
            - name: config
              mountPath: /config
            - name: configmap
              mountPath: /configmap
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "50m"
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.8.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "*"
          # Health checks - using TCP to bypass ALLOWED_HOSTS issue
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          # Resource constraints
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config-pvc
        - name: configmap
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
---
# --- 7. PodDisruptionBudget for availability during maintenance ---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homepage-pdb
  namespace: apps
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
---
# --- 8. The Ingress rule to expose Homepage to your network ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: apps
  annotations:
    gethomepage.dev/enabled: "false"
    gethomepage.dev/group: "Cluster Tools"
    gethomepage.dev/name: "Homepage"
    gethomepage.dev/icon: "homepage.png"
    gethomepage.dev/description: "This very dashboard"
spec:
  ingressClassName: nginx
  rules:
  - host: "homepage.k8s.local"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000
