# --- 1. ServiceAccount for Homepage to talk to the API Server ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: apps
---
# --- 2. The ConfigMap containing all your dashboard settings ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: apps
data:
  settings.yaml: |
    title: Homelab Dashboard
    background: 
      image: https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920
      opacity: 15
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Monitoring:
        style: row
        columns: 3
      Automation:
        style: row
        columns: 2
      AI & Tools:
        style: row
        columns: 2
      Admin:
        style: row
        columns: 2
      Media:
        style: row
        columns: 1

  services.yaml: |-
    - Monitoring:
        - Grafana:
            href: http://grafana.k8s.local
            icon: grafana.png
            description: Dashboards & Visualization
        - Prometheus:
            href: http://prometheus.k8s.local
            icon: prometheus.png
            description: Metrics Collection

    - Media:
        - Plex:
            href: http://192.168.1.221:32400/web
            icon: plex.png
            description: Media Server

    - Automation:
        - Jenkins:
            href: http://jenkins.k8s.local
            icon: jenkins.png
            description: CI/CD Pipelines
        - n8n:
            href: http://n8n.k8s.local
            icon: n8n.png
            description: Workflow Automation

    - AI & Tools:
        - OpenWebUI:
            href: http://openwebui.k8s.local
            icon: si-openai
            description: LLM Chat Interface
        - Azure MCP Tools:
            href: http://mcpo.k8s.local/docs
            icon: azure
            description: Azure MCP via OpenAPI
        - LLaMA Factory:
            href: http://llamafactory.k8s.local
            icon: mdi-brain
            description: LLM Fine-Tuning

    - Admin:
        - pgAdmin:
            href: http://pgadmin.k8s.local
            icon: si-postgresql
            description: PostgreSQL Admin
        - RedisInsight:
            href: http://redisinsight.k8s.local
            icon: si-redis
            description: Redis Admin
        - Pi-hole:
            href: http://pihole.k8s.local/admin
            icon: pi-hole.png
            description: DNS Ad Blocking

  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          show: true
        nodes:
          show: true
        namespaces:
          show: true

  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/quazmoz
    - Profiles:
        - LinkedIn:
            - abbr: LI
              href: https://www.linkedin.com/in/quinnfavo/
        - QuinnFavo:
            - abbr: DevOps
              href: https://profile.quinnfavo.com/
              
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true
    namespaces:
      show: true
      displayedNamespaces:
        - apps
        - kube-system
  custom.css: ""
  custom.js: ""
---
# --- 3. RBAC rules to allow Homepage to read Ingresses, nodes, pods, etc. ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: apps
---
# --- 4. The internal Service to expose the pod ---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
---
# --- 5. The PVC for Homepage config ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: homepage-local-pv
  resources:
    requests:
      storage: 1Gi
---
# --- 6. The Deployment to run the Homepage application ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      # Init container copies config from ConfigMap to PVC on first run
      initContainers:
        - name: init-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              # Always update config from ConfigMap
              echo "Updating config files from ConfigMap..."
              cp /configmap/* /config/
              echo "Config files updated."
          volumeMounts:
            - name: config
              mountPath: /config
            - name: configmap
              mountPath: /configmap
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.8.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.k8s.local"
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config-pvc
        - name: configmap
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
---
# --- 7. The Ingress rule to expose Homepage to your network ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: apps
  annotations:
    gethomepage.dev/enabled: "false"
    gethomepage.dev/group: "Cluster Tools"
    gethomepage.dev/name: "Homepage"
    gethomepage.dev/icon: "homepage.png"
    gethomepage.dev/description: "This very dashboard"
spec:
  ingressClassName: nginx
  rules:
  - host: "homepage.k8s.local"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000
