# --- 1. ServiceAccount for Homepage to talk to the API Server ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
---
# --- 2. The ConfigMap containing all your dashboard settings ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  # --- Homepage Settings ---
  settings.yaml: |
    title: Homelab Dashboard
    providers:
      kubernetes:
        inCluster: true
        # This block enables automatic discovery of services from Ingress annotations
        ingress:
          enabled: true
          namespace: "" # "" means scan all namespaces
          class: "nginx"

  # --- services.yaml ---
  # This file is now much cleaner. We only list services that are NOT exposed via Ingress.
  services.yaml: |
    - "Media":
        - "Plex":
            href: http://192.181.1.221:32400/web
            icon: plex.png
            description: Media Server

  # --- Widgets ---
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          cpu: true
          memory: true

  # --- Your Bookmarks ---
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/quazmoz
    - Profiles:
        - LinkedIn:
            - abbr: LI
              href: https://www.linkedin.com/in/quinnfavo/
        - QuinnFavo:
            - abbr: DevOps
              href: https://profile.quinnfavo.com/

  # --- These files are required by Homepage but can be empty ---
  docker.yaml: ""
  kubernetes.yaml: ""
  custom.css: ""
  custom.js: ""
---
# --- 3. RBAC rules to allow Homepage to read node/pod status AND INGRESSES ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "namespaces"
      - "pods"
      - "services"
      - "endpoints"
      - "configmaps"
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - "nodes"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["networking.k8s.io"]
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
---
# --- 4. The internal Service to expose the pod ---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
---
# --- 5. The Deployment to run the Homepage application ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v0.8.10"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.k8s.local"
          # This volumeMounts block is now corrected
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      # This volumes block is now corrected
      volumes:
        - name: config
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
---
# --- 6. The Ingress rule to expose Homepage to your network ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
  annotations:
    # Annotations for Homepage to discover itself
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Cluster Tools"
    gethomepage.dev/name: "Homepage"
    gethomepage.dev/icon: "homepage.png"
    gethomepage.dev/description: "This very dashboard"
spec:
  ingressClassName: nginx
  rules:
  - host: "homepage.k8s.local"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000

