# --- 1. ServiceAccount for Homepage to talk to the API Server ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
---
# --- 2. The ConfigMap containing all your dashboard settings ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  settings.yaml: |
    title: Homelab Dashboard
    debug: true
    providers:
      kubernetes:
        inCluster: true
        refreshInterval: 10

  # Other files remain the same...

  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
      # Minimal configuration
      cluster:
        show: true
      nodes:
        show: true

  kubernetes.yaml: |
    # Minimal configuration
    mode: cluster
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true
    namespaces:
      show: true
      displayedNamespaces:
        - default
        - kube-system

  # Other files remain the same...
---
# RBAC and Service remain the same...
---
# --- 5. The Deployment to run the Homepage application ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
      annotations:
        # Force pod recreation
        timestamp: "{{now}}"
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v0.6.7"  # Try an older version
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 5 && exec node /app/index.js"  # Add startup delay
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.k8s.local"
            - name: LOG_LEVEL
              value: "debug"
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc"
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
            - name: HOMEPAGE_DISABLE_CACHE
              value: "true"
          volumeMounts:
            - mountPath: /app/config
              name: config
        - name: debug
          image: busybox
          command: ['sleep', '3600']
          securityContext:
            runAsUser: 1000
      volumes:
        - name: config
          configMap:
            name: homepage-config
---

# --- 6. The Ingress rule to expose Homepage to your network ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "homepage.k8s.local"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000
