apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: pi-hole
      version: "0.2.x" # A recent stable version of the new chart
      sourceRef:
        kind: HelmRepository
        name: pi-hole # This points to the new repository we added
        namespace: flux-system
      interval: 1m
  values:
    # This is CRITICAL. It forces the pod to run only on your Pi 3 node.
    nodeSelector:
      kubernetes.io/hostname: raspberrypi3 # IMPORTANT: Use the actual hostname of your Pi 3

    # Use persistence to store the Pi-hole configuration
    persistence:
      config:
        enabled: true
        storageClassName: "local-storage"
        size: 5Gi
    
    # Set the admin password for the web UI
    adminPassword: "YourSecurePassword!"

    # Expose the DNS service via a LoadBalancer so MetalLB gives it an IP
    serviceTCP:
      type: LoadBalancer
    serviceUDP:
      type: LoadBalancer
    
    # Expose the Web UI service via an Ingress on pihole.k8s.local
    ingress:
      web:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: pihole.k8s.local
            paths:
              - path: /
                pathType: Prefix

