apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.1.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    nodeSelector:
      kubernetes.io/hostname: raspberrypi3

    # Use persistence to store the configuration
    persistence:
      config:
        enabled: true
        storageClass: "local-storage"
        size: 5Gi

    # Set the admin password for the web UI
    adminPassword: "Testingsodontworry!"

    # Expose the DNS service via a LoadBalancer so MetalLB gives it an IP
    serviceDns:
      type: LoadBalancer

    # Expose the Web UI service via a LoadBalancer as well
    serviceWeb:
      type: LoadBalancer