apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: mojo2600-pihole
        namespace: flux-system
      interval: 1m
  values:
    # Force the pod to run on Pi 3 where the local storage is
    nodeSelector:
      kubernetes.io/hostname: raspberrypi3

    # Set the admin password for the web UI
    admin:
      password: "YourSecurePassword!"

    # Use existing PVC for persistence
    persistentVolumeClaim:
      enabled: true
      existingClaim: "pihole-config"

    # DNS service configuration
    serviceDns:
      type: LoadBalancer

    # Web service configuration  
    serviceWeb:
      type: ClusterIP

    # Ingress for Web UI
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - pihole.k8s.local
