apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.20.0" # A recent stable version of this new chart
      sourceRef:
        # Point to our new repository source
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 1m
  values:
    # This chart uses a slightly different structure for values
    podDnsConfig:
      enabled: true

    # This is CRITICAL. It forces the pod to run only on your Pi 3.
    nodeSelector:
      kubernetes.io/hostname: raspberrypi3 # IMPORTANT: Use your actual hostname

    # Use persistence to store the configuration
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-storage"
      size: 5Gi

    # Set the admin password for the web UI
    # IMPORTANT: Change this to a secure password!
    adminPassword: "Testingdontworry!"

    # Expose the DNS service via a LoadBalancer
    serviceDns:
      type: LoadBalancer

    # Expose the Web UI service via a LoadBalancer
    serviceWeb:
      type: LoadBalancer