apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: pihole-local-pv
  resources:
    requests:
      storage: 5Gi
