---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: zionup-production
  labels:
    app: zionup
    component: media
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Uncomment and adjust for specific storage class
  # storageClassName: local-storage
