apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: apps
    labels:
        app.kubernetes.io/name: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:WNscZ0d4CmzGGJODCAU0VeB6+RTjkGbKC0vxD/u914G2LWTZu6bJ2XiKNcoDTWo2kENeKavJpBOrFxVf1XKM4Q==,iv:B4bG3uvrXZDMChYBhnZX6nYCdeBlf1HcdyX0oNRPaoE=,tag:/ckqKPxKgaXKcp7eUjuxXg==,type:str]
sops:
    age:
        - recipient: age1lcl4x9eckuj7skyjq26h4e70dl2qvjec3saerxzunp8z7r28e3qsd0c8d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjEzRU9Xc3BvN2hBd3Nt
            bWx0UXdlVHFJOEMza1JCQ05PWWNkcm5VUnpnCjFHbU1nMlIyRVBIZ1Zhd2s2QVh3
            OHczUlZnUXhkYUdlQ1lmQXZIOEkwQ0kKLS0tIG9iSW54YS9mWGtUaUZHOGRFNm80
            K0dwT1k4RDBmbTJmS3ZNOWV6YWRRYW8KzNLwBPY0Gap1s6buXNAxsM4KWif8v3FL
            8v9ThObeU2LEkvqtRj/hUB8jBuA0TWemFpjTnW0CiFykE+NWKxoyiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-25T09:19:02Z"
    mac: ENC[AES256_GCM,data:d9kvXMxlUUlaBVwCZ1yV4qpCTf9weyLf8K2UdPTlLnva/LPVunSlVjKyztPRaTmKiFFBmelfQaKEguccouhvOx1rCGL2Vkfur0Mu9vpWe+7s4+ykTbQKTp39NjTdoubo/CWFraZm6ccIaBY85GdAcBt0Y5ag/wi+iVHAOQ8eYmw=,iv:LEm4U7faltMYxppqCFZSKnyZDrMqI82XOplElMkQXEY=,tag:nhwLrnXMVleIUlRAeeaWgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
