apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: apps
    labels:
        app.kubernetes.io/name: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:ge9SFg45oPKXqOhgOT3TO+1L4X4Ipr6P4dd6bdt7+Ik0L1M8v9Gx1/uvbwNJdIr0YjOj3Dqt9pvCMyYewtMBIA==,iv:B4bG3uvrXZDMChYBhnZX6nYCdeBlf1HcdyX0oNRPaoE=,tag:GdWDI/Ls2vAZJWliQX1j7w==,type:str]
sops:
    age:
        - recipient: age1efqtwh58krhl5sg2je0x3hje35p3z25rjgsurzr3wty2f9px9fjq2ngqgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ3NPUmE2cGFTMHgyRDFU
            Y2J0T0ZySEJNazVFMlp5SnVORXBUWGx5alFzCmlwTk5hVVpHTTllRkdQbXMyNXNT
            WW1Va09oTE5wZ2pjVEZneUZQUVBYVDQKLS0tIEh5aVJPTTVjMzhlWlFCeDNyRk8r
            TDdsMzdsZEdSL1BOSlNOeGZOZlVVRmsKTB221puhHayoR8a50SpGWEAlh0qPtzwv
            4Jz5ysdetnudjHGHkrUTg1E5zb6P8YuJghkwAwlvcZ6iB1t4+gep4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:22:31Z"
    mac: ENC[AES256_GCM,data:DyJt/XDwSsdJ3eLetQn7tI0aH85Z5Emq8FKZbcprl0z8WtsdPiwPkaGuxTrwP9VzfTH9qGTDBAhHK60v4E5ENJKc84TJxIctwbIgoh7JThoutXJPmN0x1aF4NMmFY97CgEQh1rERzTNYjLPU/NwSyQlARmMHasPSI+i9DPrwyx0=,iv:kgTwCPaZ3jQIPDWVfAfqfwmzpi1jzZ6UX+LwWXKkYHI=,tag:iWyQgfzuvH5FgS7hmEm1PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
