apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    write:
      enabled: false
    read:
      enabled: false
    backend:
      enabled: false

    # Important: let the chart know storage type
    loki:
      storage:
        type: filesystem
      commonConfig: null

    singleBinary:
      enabled: true

      persistence:
        enabled: true
        storageClassName: "local-storage"
        size: 10Gi

      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6

      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        storage_config:
          filesystem:
            directory: /data/loki
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
