apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      # Using a specific, known-stable version
      version: "6.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # This is the critical fix. We are disabling the complex distributed
    # components and enabling the simple single-binary mode.
    write:
      enabled: false
    read:
      enabled: false
    backend:
      enabled: false
    
    singleBinary:
      enabled: true
      
      # This enables the persistent volume for the data
      persistence:
        enabled: true
        storageClassName: "local-storage"
        size: 10Gi
      
      # Ensure the Loki pod runs on the node where its storage is located
      nodeSelector:
        kubernetes.io/hostname: quinn-hpprobook430g6

      # This explicitly configures Loki's internal settings for filesystem storage
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        storage_config:
          filesystem:
            directory: /data/loki
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h

