apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-archive-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: usb-slow-storage
  volumeName: usb-logs-2-pv
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: usb-slow
