apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
  volumeName: plex-config-local-pv